version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Web
    depends_on:
      - redis
    ports:
      - 80:8080
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis
