version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Web
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=localhost
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/Nginx
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis
